#include <iostream>
#include <cmath>

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.


unsigned long int Fibonacci(unsigned int n)
{
	if (n == 1 || n == 0)
		return n;
	return (Fibonacci(n - 1) + Fibonacci(n - 2));
}

int main()
{
	unsigned long int sum = 0, i = 0, limit = 4000000;
	while (Fibonacci(i) <= limit)
	{
		if (Fibonacci(i) % 2 == 0)
			sum += Fibonacci(i);
		++i;
	}
	

	std::cout << "Sum of even valued Fibonacci numbers (below four million): " << sum << std::endl;
	return 0;
}